---
vars:
  pod_network_cidr: "10.244.0.0/16"
  kube_version: "1.34"
- name: Kubernetes Cluster Setup - Common Tasks
  hosts: all
  become: yes

  tasks:
    - name: Disable swap
      ansible.builtin.command: swapoff -a
      ignore_errors: yes

    - name: Comment out swap in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)$'
        replace: '# \1'

    - name: Enable IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Remove old Kubernetes repo
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Remove old Kubernetes keyring
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: absent

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add Kubernetes repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
        chmod 644 /etc/apt/sources.list.d/kubernetes.list
      args:
        executable: /bin/bash

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Kubernetes components
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - containerd
        state: present

    - name: Hold kubeadm, kubelet, kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        dpkg_options: "hold"

    - name: Enable and start containerd
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: started

- name: Initialize Kubernetes on Master
  hosts: k8s-master
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster
      ansible.builtin.command: >
        kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Save kubeadm init log
      ansible.builtin.copy:
        content: "{{ kubeadm_init.stdout }}"
        dest: /home/{{ ansible_user }}/kubeinit.log

    - name: Setup kubectl config for user
      ansible.builtin.shell: |
        mkdir -p /home/{{ ansible_user }}/.kube
        cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
        chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
      args:
        executable: /bin/bash

    - name: Install Flannel CNI
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash

- name: Join Worker Nodes
  hosts: k8s-worker*
  become: yes
  tasks:
    - name: Fetch join command from master
      ansible.builtin.shell: |
        grep 'kubeadm join' /home/{{ ansible_user }}/kubeinit.log
      delegate_to: k8s-master
      register: join_cmd

    - name: Join node to cluster
      ansible.builtin.shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
      args:
        executable: /bin/bash
